### PR TITLE
fix(v1.5.0) Spaces not supported in output directory path

### LINKED ISSUE #187: bug: path names in sfdx parameters not in quotes
### Summary

When retrieving logs, sfdx is called and the path parameters are not put in quotes, blanks are not escaped properly.

This causes errors when the repository path contains blanks (which I know is a bad idea but happens on windows)

### Steps To Reproduce:

1.  Have sfdx project in "c:\Users\kfett\Documents\My Repositories\test
1.  Run "Log: Load Apex Logs for Analysis" from command palette 
1.  Select any log

### Expected result

Log is loaded to VS Code

### Actual result

Error message occurs:

[error] Error: Command failed: sfdx force:apex:log:get --outputdir c:\Users\kfett\Documents\My Repositories\test\.sfdx\tools\debug\logs --logid xxxxxx
ERROR running force:apex:log:get:  Unexpected arguments: , Repositories\test\.sfdx\tools\debug\logs

### PR DESCRIPTION
**Pull request by lukecotter**
# Description

fix: Spaces not supported in output directory path
When running `Log: Load Apex Log For Analysis` command

## Type of change

- [X] Bug fix
- [ ] New feature
- [ ] Breaking change

fixes #187

### CODE REVIEW

File: lana/src/sfdx/logs/GetLogFile.ts [hunk 1]
```diff
@@ -5,15 +5,7 @@
...
-    logDir: string,
-    logId: string
-  ): Promise<string> {
-    return SFDX.apply(path, [
-      "force:apex:log:get",
-      `--outputdir ${logDir}`,
-      `--logid ${logId}`,
-    ]);
+  static async apply(path: string, logDir: string, logId: string): Promise<string> {
+    return SFDX.apply(path, ["force:apex:log:get", `--outputdir "${logDir}"`, `--logid ${logId}`]);
```
Comment (kjonesffdc) [inline lana/src/sfdx/logs/GetLogFile.ts:9]: Did you test on Windows, does it need that?
